import = ["~/.config/alacritty/rose.toml"]
live_config_reload = true

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"
[font.italic]
family = "Cascadia Code"
style = "Italic"

[window]
decorations = "None"
blur = true
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 20
y = 16
