# Options
start-at-login = true
default-root-container-layout = 'tiles'
key-mapping.preset = 'qwerty'

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true


# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'


# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# Main binds
[mode.main.binding]

# Apps Launcher

## Kitty
alt-enter = 'exec-and-forget osascript ~/work_dots/scripts/NewKittyWindow.scpt'

## Resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Layout toggle split
alt-s = 'layout tiles horizontal vertical'
# Toggle floating
alt-shift-space = 'layout floating tiling'
# Fullscreen
alt-shift-f = 'fullscreen'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Main Workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
# Removing workspace 3 since alt-3 is reserved for # on british keyboard
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

# Scratchpads
alt-u = 'workspace Term'
alt-i = 'workspace Web'
alt-o = 'workspace Comms'
alt-p = 'workspace Scratch'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']

alt-shift-u = ['move-node-to-workspace Term', 'workspace Term']
alt-shift-i = ['move-node-to-workspace Web', 'workspace Web']
alt-shift-o = ['move-node-to-workspace Comms', 'workspace Comms']
alt-shift-p = ['move-node-to-workspace Scratch', 'workspace Scratch']

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-r = 'mode resize'

[mode.resize.binding]
esc = 'mode main'
